### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by sarah-moore** [sarah-moore/math-camp-path#2]
The goal of this exercise is to create a checklist that will guide your goals for the upcoming two weeks of Math Camp. The overarching goals that we have planned for you are the following: 

- [ ] Prepare for the upcoming quarter of Political Science 403. 
- [ ] Master the basics of R and Github. 
- [ ] Develop camaraderie among your grad school peers and colleagues. 

Each of these goals will have many different steps in between. Your exercise for today, will be to complete a [couple of the modules on Github as homework](https://lab.github.com/githubtraining/first-day-on-github). You will then use the skills that you learned in these modules to create your own goal checklist in your personal repositories as .md files. Each goal should be related to one of the aforementioned key goals we have assigned for the class. To brush up on how to do this, view the source code on this page.
